### ISSUE TITLE
Will the final code for this be made public?

### ISSUE THREAD

**Issue by Toms42** [akhauriyash/Art-Em#1]
I read your article https://software.intel.com/en-us/articles/art-em-artistic-style-transfer-to-virtual-reality-final-update and I would be very interested to test this on a VR hackathon project my team is working on. Will the final code be made public ever?

**Comment by akhauriyash** [comment]
Hello,
This is out-dated work and uses a generator network which has be trained to custom styles. This further diverged to an exploration of Quantized Neural Networks from a research perspective. (https://www.researchgate.net/publication/329950131_HadaNets_Flexible_Quantization_Strategies_for_Neural_Networks)
For a hackathon project, I encourage you to check out newer sources which might serve you better and are document in a better fashion, I made this project at the start of my engineering career. 
I encourage you to inspect the following sources, which are maintained well:
1) https://github.com/lengstrom/fast-style-transfer (This might be the best.)
2) https://github.com/manuelruder/fast-artistic-videos

Wish I could help better! All the best for the hackathon! :)
